### ISSUE TITLE
Update to .rM v5 format

### ISSUE THREAD

**Issue by artagnon** [ax3l/lines-are-rusty#4]
It would be great if you could reverse-engineer the .rM v5 format. The tables [here](https://github.com/artagnon/FreelyCommute/blob/master/rM/include/ParseTable.hpp#L31-L36) seem to work, ~~modulo the `Skip` entries~~.

**Comment by davidrusu** [comment]
I have a working implementation on my branch, I'll see if I can get it polished and PR'd this week/weekend

also adds SVG output: https://github.com/ax3l/lines-are-rusty/compare/develop...davidrusu:support-v5-and-svg-output

**Comment by danshick** [comment]
I've started a different implementation over at https://github.com/danshick/relineate. Feel free to steal from this if it helps at all.
